jobs:
  build:
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 30
      TEST_TIMES_CACHE_PRESENT: false
    outputs:
      average_time_per_instance: ${{ steps.test_times_cache_present_init.outputs.average_time_per_instance
        }}
      matrix_array: ${{ steps.test_times_cache_present_init.outputs.matrix_array }}
      number_of_matrix_instances: ${{ steps.test_times_cache_present_init.outputs.number_of_matrix_instances
        }}
      test_times_cache_present: ${{ steps.test_times_cache_present_init.outputs.test_times_cache_present
        }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set env variables
      uses: ./.github/workflows/composites/env-variables
    - continue-on-error: true
      id: jdk_17
      if: env.BASE_BRANCH == 'main' || env.BASE_BRANCH == '3.0.x'
      name: setup project jdk-17
      uses: ./.github/workflows/composites/setup-jdk17
    - continue-on-error: true
      name: cache local maven repository
      uses: ./.github/workflows/composites/cache
    - continue-on-error: true
      name: Show caches
      uses: actions/github-script@v6
      with:
        script: "const caches = await github.rest.actions.getActionsCacheList({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n})\nfor (const\
          \ cache of caches.data.actions_caches) {\n  console.log(cache)\n}  \n"
    - continue-on-error: true
      name: maven build with dry-run for tests
      uses: ./.github/workflows/composites/maven-build-with-dry-run-for-tests
    - continue-on-error: true
      id: restore_test_times_cache
      name: restore test times cache if it exists
      uses: actions/cache/restore@v4
      with:
        key: ${{ runner.os }}-spring-cloud-k8s-existing-test-times-cache-${{ github.run_id
          }}
        path: /tmp/sorted.txt
        restore-keys: ${{ runner.os }}-spring-cloud-k8s-existing-test-times-cache-
    - continue-on-error: true
      id: check_files
      name: check test times cache exists
      uses: andstor/file-existence-action@v2
      with:
        files: /tmp/sorted.txt
    - continue-on-error: true
      if: steps.check_files.outputs.files_exists == 'true'
      name: show existing cache of test times
      run: cat /tmp/sorted.txt
      shell: bash
    - continue-on-error: true
      if: steps.check_files.outputs.files_exists == 'true'
      name: compute matrix related fields when cache is present
      uses: ./.github/workflows/composites/matrix-bounds-on-test-times-cache-hit
    - continue-on-error: true
      id: test_times_cache_present_init
      name: matrix related variables when cache is present
      run: 'echo "test_times_cache_present=${{ env.TEST_TIMES_CACHE_PRESENT }}" >>
        $GITHUB_OUTPUT

        echo "number_of_matrix_instances=${{ env.NUMBER_OF_MATRIX_INSTANCES }}" >>
        $GITHUB_OUTPUT

        echo "matrix_array=${{ env.MATRIX_ARRAY }}" >> $GITHUB_OUTPUT

        echo "average_time_per_instance=${{ env.AVERAGE_TIME_PER_INSTANCE }}" >> $GITHUB_OUTPUT

        '
  save_test_times_when_cache_missing:
    needs:
    - build
    - test_when_cache_missing
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: compute and save running time of tests
      uses: ./.github/workflows/composites/test-times
  save_test_times_when_cache_present:
    needs:
    - build
    - test_when_cache_present
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: compute and save running time of tests
      uses: ./.github/workflows/composites/test-times
  test_when_cache_missing:
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 30
    if: needs.build.outputs.test_times_cache_present == 'false'
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: clean space
      uses: ./.github/workflows/composites/clean-space
    - continue-on-error: true
      name: set env variables
      uses: ./.github/workflows/composites/env-variables
    - continue-on-error: true
      if: env.BASE_BRANCH == 'main' || env.BASE_BRANCH == '3.0.x'
      name: setup project jdk-17
      uses: ./.github/workflows/composites/setup-jdk17
    - continue-on-error: true
      name: pre-test-actions
      uses: ./.github/workflows/composites/pre-test-actions
    - continue-on-error: true
      env:
        CURRENT_INDEX: ${{ matrix.current_index }}
        NUMBER_OF_JOBS: ${{ matrix.number_of_jobs }}
      name: compute single step test bounds
      uses: ./.github/workflows/composites/test-bounds
    - continue-on-error: true
      name: testcontainers reuse support
      run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties
      shell: bash
    - continue-on-error: true
      env:
        CURRENT_INDEX: ${{ matrix.current_index }}
      name: run and save individual test times
      uses: ./.github/workflows/composites/run-and-save-test-times-when-cache-missing
    strategy:
      fail-fast: true
      matrix:
        current_index:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        number_of_jobs:
        - 32
    timeout-minutes: 120
  test_when_cache_present:
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 30
    if: needs.build.outputs.test_times_cache_present == 'true'
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: clean space
      uses: ./.github/workflows/composites/clean-space
    - continue-on-error: true
      name: set env variables
      uses: ./.github/workflows/composites/env-variables
    - continue-on-error: true
      if: env.BASE_BRANCH == 'main' || env.BASE_BRANCH == '3.0.x'
      name: setup project jdk-17
      uses: ./.github/workflows/composites/setup-jdk17
    - continue-on-error: true
      name: pre-test-actions
      uses: ./.github/workflows/composites/pre-test-actions
    - continue-on-error: true
      name: testcontainers reuse support
      run: echo "testcontainers.reuse.enable=true" > ~/.testcontainers.properties
      shell: bash
    - continue-on-error: true
      env:
        AVERAGE_TIME_PER_INSTANCE: ${{ matrix.average_time_per_instance }}
        CURRENT_INDEX: ${{ matrix.current_index }}
        NUMBER_OF_JOBS: ${{ matrix.number_of_jobs }}
      name: run and save test times when cache is present
      uses: ./.github/workflows/composites/run-and-save-test-times-when-cache-present
    strategy:
      fail-fast: true
      matrix:
        average_time_per_instance:
        - ${{ fromJSON(needs.build.outputs.average_time_per_instance) }}
        current_index:
        - ${{ fromJSON(needs.build.outputs.matrix_array) }}
        number_of_jobs:
        - ${{ fromJSON(needs.build.outputs.number_of_matrix_instances) }}
    timeout-minutes: 120
name: github-workflow
on:
  repository_dispatch:
    types: trigger-ga___maven.yaml
